name: pygeogrids
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - boost-cpp=1.74.0
  - bzip2=1.0.8
  - c-ares=1.17.1
  - ca-certificates=2021.5.30
  - cairo=1.16.0
  - certifi=2021.5.30
  - cfitsio=3.470
  - cftime=1.5.0
  - curl=7.77.0
  - expat=2.4.1
  - fontconfig=2.13.1
  - freetype=2.10.4
  - freexl=1.0.6
  - gdal=3.3.1
  - geos=3.9.1
  - geotiff=1.6.0
  - gettext=0.19.8.1
  - giflib=5.2.1
  - hdf4=4.2.15
  - hdf5=1.10.6
  - icu=68.1
  - jbig=2.1
  - jpeg=9d
  - json-c=0.15
  - kealib=1.4.14
  - krb5=1.19.1
  - ld_impl_linux-64=2.36.1
  - lerc=2.2.1
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcurl=7.77.0
  - libdap4=3.20.6
  - libdeflate=1.7
  - libedit=3.1.20191231
  - libev=4.33
  - libffi=3.3
  - libgcc-ng=9.3.0
  - libgdal=3.3.1
  - libgfortran-ng=9.3.0
  - libgfortran5=9.3.0
  - libglib=2.68.3
  - libgomp=9.3.0
  - libiconv=1.16
  - libkml=1.3.0
  - liblapack=3.9.0
  - libnetcdf=4.8.0
  - libnghttp2=1.43.0
  - libopenblas=0.3.15
  - libpng=1.6.37
  - libpq=13.3
  - librttopo=1.1.0
  - libspatialite=5.0.1
  - libssh2=1.9.0
  - libstdcxx-ng=9.3.0
  - libtiff=4.3.0
  - libuuid=2.32.1
  - libwebp-base=1.2.0
  - libxcb=1.13
  - libxml2=2.9.12
  - libzip=1.8.0
  - lz4-c=1.9.3
  - ncurses=6.2
  - netcdf4=1.5.7
  - numpy=1.21.1
  - openjpeg=2.4.0
  - openssl=1.1.1k
  - pandas=1.3.0
  - pcre=8.45
  - pip=21.1.3
  - pixman=0.40.0
  - poppler=21.03.0
  - poppler-data=0.4.10
  - postgresql=13.3
  - proj=8.0.1
  - pthread-stubs=0.4
  - pykdtree=1.3.4
  - pyproj=3.1.0
  - python=3.9.6
  - python-dateutil=2.8.2
  - python_abi=3.9
  - pytz=2021.1
  - readline=8.1
  - setuptools=49.6.0
  - six=1.16.0
  - sqlite=3.36.0
  - tiledb=2.3.2
  - tk=8.6.10
  - tzcode=2021a
  - tzdata=2021a
  - wheel=0.36.2
  - xerces-c=3.2.3
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.10
  - xorg-libsm=1.2.3
  - xorg-libx11=1.7.2
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxrender=0.9.10
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.5
  - zlib=1.2.11
  - zstd=1.5.0
  - pip:
      - alabaster==0.7.12
      - attrs==21.2.0
      - babel==2.9.1
      - charset-normalizer==2.0.3
      - coverage==5.5
      - docutils==0.16
      - idna==3.2
      - imagesize==1.2.0
      - iniconfig==1.1.1
      - jinja2==3.0.1
      - markupsafe==2.0.1
      - packaging==21.0
      - pluggy==0.13.1
      - py==1.10.0
      - pygments==2.9.0
      - pyparsing==2.4.7
      - pytest==6.2.4
      - pytest-cov==2.12.1
      - requests==2.26.0
      - snowballstemmer==2.1.0
      - sphinx==4.1.1
      - sphinx-rtd-theme==0.5.2
      - sphinxcontrib-applehelp==1.0.2
      - sphinxcontrib-devhelp==1.0.2
      - sphinxcontrib-htmlhelp==2.0.0
      - sphinxcontrib-jsmath==1.0.1
      - sphinxcontrib-qthelp==1.0.3
      - sphinxcontrib-serializinghtml==1.1.5
      - toml==0.10.2
      - urllib3==1.26.6