name: pygeogrids
channels:
  - conda-forge
dependencies:
  - numpy
  - pandas
  - netcdf4
  - geos
  - gdal
  - pyproj
  - pykdtree
  - scipy
  - ipykernel
  - pip
  - pip:
    - sphinx==4.0.3  # https://github.com/spatialaudio/nbsphinx/issues/584, when this is resolved this line can be deleted to use the latest version.
    - nbsphinx
    - sphinx_rtd_theme
    - pytest
    - pytest-cov