name: pygeogrids
channels:
  - conda-forge
dependencies:
  - numpy
  - pandas
  - netcdf4
  - geos
  - gdal
  - pyproj
  - pykdtree
  - scipy
  - ipykernel
  - pip
  - pip:
    - sphinx
    - nbsphinx
    - sphinx_rtd_theme
    - pytest
    - pytest-cov
