name: pygeogrids
dependencies:
- curl=7.49.0
- gdal=2.1.0
- geos=3.5.0
- geotiff=1.4.1
- hdf4=4.2.12
- hdf5=1.8.17
- jbig=2.1
- kealib=1.4.6
- libnetcdf=4.4.1
- libgdal=2.1.0
- mkl=11.3.3=0
- netcdf4=1.2.4
- numpy=1.11.0
- openssl=1.0.2h
- pip=8.1.1
- proj4=4.9.2
- py=1.4.31
- pyproj=1.9
- pytest=2.9.1
- python=3.4
- readline=6.2
- setuptools=21.2.1
- sqlite=3.13.0
- tk=8.5.18=0
- xz=5.2.2=1
- wheel=0.29.0
- zlib=1.2.8
- pip:
  - pykdtree==1.1.1

