name: pygeogrids
dependencies:
  - ipykernel
  - pip
  - pip:
    - mock
    - numpydoc
    - sphinx==4.0.3  # https://github.com/spatialaudio/nbsphinx/issues/584, when this is resolved this line can be deleted to use the latest version.
    - nbsphinx
    - sphinx_rtd_theme